Traceback (most recent call last):
  File "train.py", line 80, in <module>
    actor_loss, critic_loss =  ppo.update(replay_buffer)
  File "/home/ssbl/Desktop/PPO/ppo.py", line 79, in update
    actor_loss.backward()
  File "/home/ssbl/anaconda3/envs/ml/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ssbl/anaconda3/envs/ml/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 1.69 GiB (GPU 0; 10.91 GiB total capacity; 6.76 GiB already allocated; 1.33 GiB free; 15.82 MiB cached)
